// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShipmentService.API.Data;

#nullable disable

namespace ShippingService.Migrations
{
    [DbContext(typeof(ShipmentServiceDbContext))]
    [Migration("20230611153338_Seeded Data")]
    partial class SeededData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShipmentService.API.Data.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 10.0,
                            Length = 10.0,
                            ShipmentId = 1,
                            Weight = 10.0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 2,
                            Height = 20.0,
                            Length = 20.0,
                            ShipmentId = 2,
                            Weight = 20.0,
                            Width = 20.0
                        });
                });

            modelBuilder.Entity("ShipmentService.API.Data.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarrierServiceId")
                        .HasColumnType("text");

                    b.Property<string>("ShipmentId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarrierServiceId = "fedexAIR",
                            ShipmentId = "FedEX"
                        },
                        new
                        {
                            Id = 2,
                            CarrierServiceId = "fedexGROUND",
                            ShipmentId = "FedEX"
                        });
                });

            modelBuilder.Entity("ShipmentService.API.Data.Package", b =>
                {
                    b.HasOne("ShipmentService.API.Data.Shipment", "Shipment")
                        .WithOne("Package")
                        .HasForeignKey("ShipmentService.API.Data.Package", "ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentService.API.Data.Shipment", b =>
                {
                    b.Navigation("Package");
                });
#pragma warning restore 612, 618
        }
    }
}
